export const AUDIT_EVENTS = Object.freeze({
  AUTH_LOGIN_SUCCEEDED: 'AUTH_LOGIN_SUCCEEDED',
  AUTH_LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  AUTH_LOGIN_RATE_LIMITED: 'AUTH_LOGIN_RATE_LIMITED',
  AUTH_REFRESH_SUCCEEDED: 'AUTH_REFRESH_SUCCEEDED',
  AUTH_REFRESH_FAILED: 'AUTH_REFRESH_FAILED',
  AUTH_REFRESH_REUSE_DETECTED: 'AUTH_REFRESH_REUSE_DETECTED',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_LOGOUT_ALL: 'AUTH_LOGOUT_ALL',
  AUTH_SESSION_REVOKED: 'AUTH_SESSION_REVOKED',
  AUTH_PASSWORD_CHANGED: 'AUTH_PASSWORD_CHANGED',

  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_ENABLED: 'USER_ENABLED',
  USER_DISABLED: 'USER_DISABLED',
  USER_PASSWORD_RESET: 'USER_PASSWORD_RESET',
  USER_SESSIONS_REVOKED: 'USER_SESSIONS_REVOKED',
  USER_PERMISSION_CHANGED: 'USER_PERMISSION_CHANGED',
  USER_ACCOUNT_ACCESS_CHANGED: 'USER_ACCOUNT_ACCESS_CHANGED',

  CLIENT_PII_REVEALED: 'CLIENT_PII_REVEALED',

  WHATSAPP_ACCOUNT_DELETED: 'WHATSAPP_ACCOUNT_DELETED',
} as const);

export type AuditEvent = (typeof AUDIT_EVENTS)[keyof typeof AUDIT_EVENTS];

export const AUDIT_EVENT_VALUES = Object.freeze(Object.values(AUDIT_EVENTS)) as readonly [
  AuditEvent,
  ...AuditEvent[],
];
